env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
globals:
  __filename: true
  __dirname: true
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    experrimentalObjectRestSpread: true
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules: 
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - never
  linebreak-style:
    - error
    - unix
  no-console: 0
